"""edit car model

Revision ID: 0731927610d1
Revises: 3e67e281de48
Create Date: 2023-08-21 19:21:28.243316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0731927610d1'
down_revision: Union[str, None] = '3e67e281de48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('one_day', sa.Integer(), nullable=True),
    sa.Column('two_three_days', sa.Integer(), nullable=True),
    sa.Column('four_seven_days', sa.Integer(), nullable=True),
    sa.Column('eight_fourteen_days', sa.Integer(), nullable=True),
    sa.Column('fifteen_thirty_days', sa.Integer(), nullable=True),
    sa.Column('weekend', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_id'), 'price', ['id'], unique=False)
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('air_cold', sa.String(length=50), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('fuel_rate', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    op.drop_index('ix_cars_id', table_name='cars')
    op.drop_table('cars')
    op.drop_index('ix_prices_id', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('prices_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('one_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('two_three_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('four_seven_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eight_fourteen_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fifteen_thirty_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekend', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deposit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prices_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_prices_id', 'prices', ['id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transmission', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('air_cold', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('power', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fuel_rate', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name='cars_price_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.create_index('ix_cars_id', 'cars', ['id'], unique=False)
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_price_id'), table_name='price')
    op.drop_table('price')
    # ### end Alembic commands ###
