"""Добавлены необязательные поля в модель пользователя

Revision ID: 67bba9a4c829
Revises: 85a1891bae93
Create Date: 2023-09-17 18:09:58.546099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67bba9a4c829"
down_revision: Union[str, None] = "85a1891bae93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column("user", sa.Column("address", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "address")
    op.drop_column("user", "phone_number")
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###
