"""add field for calculate booking

Revision ID: 85a1891bae93
Revises: 052b6962111f
Create Date: 2023-09-16 07:39:33.045701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85a1891bae93"
down_revision: Union[str, None] = "052b6962111f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookingcar", sa.Column("total_amount", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookingcar", "total_amount")
    # ### end Alembic commands ###
