"""initial models

Revision ID: 956cafc45468
Revises: 0435282b788f
Create Date: 2023-08-27 13:26:09.817334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956cafc45468'
down_revision: Union[str, None] = '0435282b788f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('one_day', sa.Integer(), nullable=True),
    sa.Column('two_three_days', sa.Integer(), nullable=True),
    sa.Column('four_seven_days', sa.Integer(), nullable=True),
    sa.Column('eight_fourteen_days', sa.Integer(), nullable=True),
    sa.Column('fifteen_thirty_days', sa.Integer(), nullable=True),
    sa.Column('weekend', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_id'), 'price', ['id'], unique=False)
    op.create_index(op.f('ix_price_name'), 'price', ['name'], unique=False)
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('air_cold', sa.String(length=50), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('fuel_rate', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_brand'), 'car', ['brand'], unique=False)
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_index(op.f('ix_car_brand'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_price_name'), table_name='price')
    op.drop_index(op.f('ix_price_id'), table_name='price')
    op.drop_table('price')
    # ### end Alembic commands ###
