"""Add json field to booking

Revision ID: abcea1130de5
Revises: 0a88970c19c3
Create Date: 2023-09-23 18:03:07.017704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abcea1130de5"
down_revision: Union[str, None] = "0a88970c19c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookingcar", sa.Column("additional_services", sa.JSON(), nullable=True)
    )
    op.drop_column("bookingcar", "additional_services_airport")
    op.drop_column("bookingcar", "additional_services_railway_station")
    op.drop_column("bookingcar", "additional_services_add_driver")
    op.drop_column("bookingcar", "additional_services_your_address")
    op.drop_column("bookingcar", "additional_services_washing")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookingcar",
        sa.Column(
            "additional_services_washing",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bookingcar",
        sa.Column(
            "additional_services_your_address",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bookingcar",
        sa.Column(
            "additional_services_add_driver",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bookingcar",
        sa.Column(
            "additional_services_railway_station",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bookingcar",
        sa.Column(
            "additional_services_airport",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("bookingcar", "additional_services")
    # ### end Alembic commands ###
