"""add BookingCar model

Revision ID: e7cbd621d3ef
Revises: bc3a432527d5
Create Date: 2023-09-11 16:04:20.001500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7cbd621d3ef"
down_revision: Union[str, None] = "bc3a432527d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookingcar",
        sa.Column("from_reserve", sa.DateTime(), nullable=True),
        sa.Column("to_reserve", sa.DateTime(), nullable=True),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["car.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookingcar")
    # ### end Alembic commands ###
