"""add_field_application_date_in_booking_model

Revision ID: fedc1fe6cf96
Revises: abcea1130de5
Create Date: 2023-10-02 18:10:39.854757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedc1fe6cf96'
down_revision: Union[str, None] = 'abcea1130de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookingcar', sa.Column('application_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookingcar', 'application_date')
    # ### end Alembic commands ###
